In [3]:
import pandas as pd

# Picnic AI challenge:
## Data exploration and preparation
### to use in custom computer vision experiment

In [4]:
train_metadata = pd.read_csv('train.tsv', sep='\t', header=0)

In [5]:
train_metadata.describe()

             file                    label
count        7259                     7259
unique       7259                       25
top     5636.jpeg  Bananas, apples & pears
freq            1                      851

In [6]:
train_metadata.groupby(["label"]).count()

                                            file
label
Asparagus, string beans & brussels sprouts   129
Bananas, apples & pears                      851
Bell peppers, zucchinis & eggplants          543
Berries & cherries                           273
Broccoli, cauliflowers, carrots & radish     248
Cheese                                       288
Citrus fruits                                307
Cucumber, tomatoes & avocados                515
Eggs                                         251
Fish                                          94
Fresh bread                                  131
Fresh herbs                                  204
Kiwis, grapes & mango                        409
Lunch & Deli Meats                           170
Milk                                         140
Minced meat & meatballs                      342
Nectarines, peaches & apricots               182
Onions, leek, garlic & beets                 114
Pineapples, melons & passion fruit           150
Pork, beef & lamb                            481
Potatoes                                     218
Poultry                                      241
Pre-baked breads                             546
Pudding, yogurt & quark                      243
Salad & cress                                189

In [7]:
train_metadata.head()

     file                                label
0   0.png              Bananas, apples & pears
1   1.png                   Berries & cherries
2  2.jpeg                    Pork, beef & lamb
3   3.png                   Berries & cherries
4  4.jpeg  Bell peppers, zucchinis & eggplants

In [ ]:
# Preprocessing steps:
import os
import shutil

# sort images by label
for row, column in train_metadata.iterrows():
    if not os.path.exists('sorted_classes'):
        os.makedirs('sorted_classes')
    if not os.path.exists('sorted_classes/' + column.label):
        os.makedirs('sorted_classes/' + column.label)
    # Change to match proper directory of data
    data_from = './train/The Picnic Hackathon 2019/train/' + column.file
    data_to = './sorted_classes/' + column.label + '/' + column.file
    
    shutil.copyfile(data_from, data_to)